name: flutter_notemus_example
description: Demonstrates how to use the flutter_notemus package.
publish_to: 'none'

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_notemus:
    path: ../
  pdf: ^3.10.4
  printing: ^5.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
